server:
  port: 8080

spring:
  application:
    name: library-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/common/**, /api/student/register, /api/student/user/**, /api/student/notification/**, /uploads/**
            
        - id: reservation-service-student
          uri: http://localhost:8082
          predicates:
            - Path=/api/student/lab/**, /api/student/seat/**, /api/student/book/**, /api/student/feedback/**

        - id: reservation-service-admin
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/**
            
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
